import { DownloadIcon } from "lucide-react";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { renderQrSvg } from "@/lib/links/qr";

export async function QrCodeCard({ slug, url }: { slug: string; url: string }) {
  // Markup generated by the qrcode library from our own URL; it contains no user-supplied HTML.
  const svg = await renderQrSvg(url);

  return (
    <Card>
      <CardHeader>
        <CardTitle>QR code</CardTitle>
        <CardDescription>
          Opens {url}, so scans are counted and you can change the destination without reprinting.
        </CardDescription>
      </CardHeader>
      <CardContent className="flex flex-col items-center gap-4">
        <div
          role="img"
          aria-label={`QR code for ${url}`}
          className="aspect-square w-full max-w-56 overflow-hidden rounded-lg bg-white [&_svg]:block [&_svg]:size-full"
          dangerouslySetInnerHTML={{ __html: svg }}
        />
        <div className="flex gap-2">
          <a href={`/api/qr/${slug}?format=svg`} download className={buttonVariants({ variant: "outline", size: "sm" })}>
            <DownloadIcon />
            SVG (print)
          </a>
          <a href={`/api/qr/${slug}?format=png`} download className={buttonVariants({ variant: "outline", size: "sm" })}>
            <DownloadIcon />
            PNG
          </a>
        </div>
      </CardContent>
    </Card>
  );
}
